export default {
  no_data: "No data available for the day – are we still waiting for the prices?",
  no_data_attributes: "Your entity has no data attributes - see the readme",
  no_data_prices: "Your entity has no prices in the correct format - see the readme",
  missing_price: "Please specify 'price' sensor in the config",
  label_today_price: "Today's price",
  label_time_nextDay: "Price range",
  label_average_price: "Average Price",
  label_price: "Price",
  label_day: "Day",
  label_start: "Start",
  label_end: "End",
  label_duration: "Duration",
  label_name: "Name",
  unit_cent: "Cent",
  label_tomorrow_price: "Tomorrow's price",
  editor_theme_light: "Light",
  editor_theme_dark: "Dark",
  editor_theme_system: "System",
  editor_price_label: "Price sensor",
  editor_price_desc: "Sensor that contains the current price (in attribute data)",
  editor_average_label: "Optional: Average value",
  editor_average_desc: "Number (e.g. 0.225) indicating the average price (optional)",
  editor_theme_label: "Theme",
  editor_theme_desc: "Display mode of the card.",
  editor_start_today: "Today",
  editor_start_tomorrow: "Tomorrow",
  editor_start_yesterday: "Yesterday",
  editor_start_view_label: "Start View",
  editor_start_view_desc: "The view that should be displayed by default",
  editor_view_mode_label: "View Mode",
  editor_currency_label: "Currency",
  editor_currency_desc: "Specify a custom currency",
  editor_day_switch_label: "Day Switch",
  editor_day_switch_desc: "Shows or hides the day switch",
  editor_cheap_times_label: "Cheap Times",
  editor_cheap_times_desc: "Display of cheap time intervals",
  editor_graph_days_label: "Visible Days (Graph)",
  editor_graph_days_desc: "Select which days to display in graph mode",
};