export default {
  no_data: "Aucune donnée disponible pour la journée – attendons les prix ?",
  no_data_attributes: "Votre entité n'a pas d'attributs de données - voir le readme",
  no_data_prices: "Votre entité n'a pas de prix au format correct - voir le readme",
  missing_price: "Veuillez indiquer le capteur 'price' dans la configuration",
  label_today_price: "Prix du jour",
  label_time_nextDay: "Plage de prix",
  label_average_price: "Prix moyen",
  label_price: "Prix",
  label_day: "Jour",
  label_start: "Début",
  label_end: "Fin",
  label_duration: "Durée",
  label_name: "Nom",
  unit_cent: "Centimes",
  label_tomorrow_price: "Prix de demain",
  editor_theme_light: "Clair",
  editor_theme_dark: "Sombre",
  editor_theme_system: "Système",
  editor_price_label: "Capteur de prix",
  editor_price_desc: "Capteur qui contient le prix actuel (dans l’attribut data)",
  editor_average_label: "Optionnel : Valeur moyenne",
  editor_average_desc: "Nombre (p. ex. 0.225) indiquant le prix moyen (optionnel)",
  editor_theme_label: "Thème",
  editor_theme_desc: "Mode d’affichage de la carte.",
  editor_start_today: "Aujourd’hui",
  editor_start_tomorrow: "Demain",
  editor_start_yesterday: "Hier",
  editor_start_view_label: "Vue de démarrage",
  editor_start_view_desc: "Vue à afficher par défaut",
  editor_view_mode_label: "Mode d’affichage",
  editor_currency_label: "Monnaie",
  editor_currency_desc: "Indiquez une devise personnalisée",
  editor_day_switch_label: "Commutateur de jour",
  editor_day_switch_desc: "Affiche ou masque le commutateur de jour",
  editor_cheap_times_label: "Heures avantageuses",
  editor_cheap_times_desc: "Affichage des intervalles horaires avantageux",
  editor_graph_days_label: "Jours visibles (Graphique)",
  editor_graph_days_desc: "Sélectionnez les jours à afficher en mode graphique",
};