export default {
  no_data: "Geen gegevens voor vandaag – wachten we nog op de prijzen?",
  no_data_attributes: "Je entiteit heeft geen data-attributen – zie readme",
  no_data_prices: "Je entiteit heeft geen prijzen in het juiste formaat – zie readme",
  missing_price: "Geef alstublieft de 'price'-sensor op in de configuratie",
  label_today_price: "Prijs van vandaag",
  label_time_nextDay: "Tijdsperiode",
  unit_cent: "Cent",
  label_tomorrow_price: "Prijs van morgen",
  label_average_price: "Gemiddelde prijs",
  label_price: "Prijs",
  label_day: "Dag",
  label_start: "Start",
  label_end: "Einde",
  label_duration: "Duur",
  label_name: "Naam",
  editor_theme_light: "Licht",
  editor_theme_dark: "Donker",
  editor_theme_system: "Systeem",
  editor_price_label: "Prijs-sensor",
  editor_price_desc: "Sensor die de actuele prijs bevat (in data-attributen)",
  editor_average_label: "Optioneel: Gemiddelde waarde",
  editor_average_desc: "Getal (bijv. 0.225) dat de gemiddelde prijs aangeeft (optioneel)",
  editor_theme_label: "Thema",
  editor_theme_desc: "Weergavemodus van de kaart.",
  editor_start_today: "Vandaag",
  editor_start_tomorrow: "Morgen",
  editor_start_yesterday: "Gisteren",
  editor_start_view_label: "Startweergave",
  editor_start_view_desc: "Weergave die standaard wordt getoond",
  editor_view_mode_label: "Weergavemodus",
  editor_currency_label: "Valuta",
  editor_currency_desc: "Eigen valuta opgeven",
  editor_day_switch_label: "Dagwisselaar",
  editor_day_switch_desc: "Toont of verbergt de dagwisselaar",
  editor_cheap_times_label: "Goedkope tijden",
  editor_cheap_times_desc: "Weergave van goedkope tijdsintervallen",
  editor_graph_days_label: "Zichtbare dagen (Grafiek)",
  editor_graph_days_desc: "Selecteer welke dagen in de grafiekmodus worden weergegeven",
};
