export default {
  no_data: "Ingen data for dagen – venter vi fortsatt på prisene?",
  no_data_attributes: "Enheten din har ingen data-attributter – se readme",
  no_data_prices: "Enheten din har ingen priser i riktig format – se readme",
  missing_price: "Vennligst oppgi 'price'-sensoren i konfigurasjonen",
  label_today_price: "Dagens pris",
  label_time_nextDay: "Tidsintervall",
  unit_cent: "Cent",
  label_tomorrow_price: "Morgendagens pris",
  label_average_price: "Gjennomsnittspris",
  label_price: "Pris",
  label_day: "Dag",
  label_start: "Start",
  label_end: "Slutt",
  label_duration: "Varighet",
  label_name: "Navn",
  editor_theme_light: "Lyst",
  editor_theme_dark: "Mørkt",
  editor_theme_system: "System",
  editor_price_label: "Pris-sensor",
  editor_price_desc: "Sensor som inneholder gjeldende pris (i data-attributter)",
  editor_average_label: "Valgfritt: Gjennomsnittsverdi",
  editor_average_desc: "Tall (f.eks. 0.225) som viser gjennomsnittsprisen (valgfritt)",
  editor_theme_label: "Tema",
  editor_theme_desc: "Visningsmodus for kortet.",
  editor_start_today: "I dag",
  editor_start_tomorrow: "I morgen",
  editor_start_yesterday: "I går",
  editor_start_view_label: "Startvisning",
  editor_start_view_desc: "Visningen som vises som standard",
  editor_view_mode_label: "Visningsmodus",
  editor_currency_label: "Valuta",
  editor_currency_desc: "Angi egen valuta",
  editor_day_switch_label: "Dagveksler",
  editor_day_switch_desc: "Viser eller skjuler dagveksleren",
  editor_cheap_times_label: "Billige tider",
  editor_cheap_times_desc: "Visning av billige tidsintervaller",
  editor_graph_days_label: "Synlige dager (Graf)",
  editor_graph_days_desc: "Velg hvilke dager som skal vises i grafmodus",
};
